# Generated by Django 6.1.1 on 2026-09-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProducts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_qty',
            new_name='qty',
        ),
    ]
