# Generated by Django 6.1.1 on 2026-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_qty',
            field=models.IntegerField(),
        ),
    ]
