# Generated by Django 6.1.1 on 2026-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
