# Generated by Django 6.1.1 on 2026-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMovies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
